#pragma once

#include "build_config/build_profiles.hpp"

// Compile-time feature gates.
//
// These defaults are profile-driven, but every value can still be overridden
// from platformio.ini or a private local build config with -DTRACKER_ENABLE_...=.
// Keep them as macros because runtime code uses them in #if blocks.
//
// The profile matrix is intentionally written as explicit #if/#elif blocks.
// This is a little longer than boolean macro expressions such as
// (!TRACKER_BUILD_IS_SLIM), but it makes the Debug/Production/Slim contract
// obvious and avoids hiding product policy inside preprocessor arithmetic.

#if TRACKER_BUILD_IS_DEBUG

#ifndef TRACKER_ENABLE_SERIAL_CONSOLE
#define TRACKER_ENABLE_SERIAL_CONSOLE 1
#endif
#ifndef TRACKER_ENABLE_BOOT_DELAY
#define TRACKER_ENABLE_BOOT_DELAY 1
#endif
#ifndef TRACKER_ENABLE_BOOT_BANNER
#define TRACKER_ENABLE_BOOT_BANNER 1
#endif
#ifndef TRACKER_ENABLE_SERIAL_CLI
#define TRACKER_ENABLE_SERIAL_CLI 1
#endif
#ifndef TRACKER_ENABLE_FULL_CLI
#define TRACKER_ENABLE_FULL_CLI 1
#endif
#ifndef TRACKER_ENABLE_BASIC_CLI
#define TRACKER_ENABLE_BASIC_CLI 1
#endif
#ifndef TRACKER_ENABLE_SETUP_COMMANDS
#define TRACKER_ENABLE_SETUP_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_CONFIG_COMMANDS
#define TRACKER_ENABLE_CONFIG_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_NETWORK_COMMANDS
#define TRACKER_ENABLE_NETWORK_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_COMMANDS
#define TRACKER_ENABLE_SLIMEVR_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_CALIBRATION_COMMANDS
#define TRACKER_ENABLE_CALIBRATION_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_TEST_COMMANDS
#define TRACKER_ENABLE_TEST_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_WIFI_SCAN_COMMANDS
#define TRACKER_ENABLE_WIFI_SCAN_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_MAG_COMMANDS
#define TRACKER_ENABLE_MAG_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_SERIAL_STREAM
#define TRACKER_ENABLE_SERIAL_STREAM 1
#endif
#ifndef TRACKER_ENABLE_MACHINE_LOG
#define TRACKER_ENABLE_MACHINE_LOG 1
#endif
#ifndef TRACKER_ENABLE_STATIC_TEST
#define TRACKER_ENABLE_STATIC_TEST 1
#endif
#ifndef TRACKER_ENABLE_RUNTIME_TEST
#define TRACKER_ENABLE_RUNTIME_TEST 1
#endif
#ifndef TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS
#define TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS 1
#endif
#ifndef TRACKER_ENABLE_HOTPATH_PERF
#define TRACKER_ENABLE_HOTPATH_PERF 1
#endif
#ifndef TRACKER_ENABLE_LOOP_TIMING
#define TRACKER_ENABLE_LOOP_TIMING 1
#endif
#ifndef TRACKER_ENABLE_BOOT_HEARTBEAT
#define TRACKER_ENABLE_BOOT_HEARTBEAT 1
#endif
#ifndef TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT
#define TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT 1
#endif
#ifndef TRACKER_ENABLE_STATUS_LED
#define TRACKER_ENABLE_STATUS_LED 1
#endif
#ifndef TRACKER_ENABLE_TAP_RUNTIME
#define TRACKER_ENABLE_TAP_RUNTIME 1
#endif
#ifndef TRACKER_ENABLE_BATTERY_RUNTIME
#define TRACKER_ENABLE_BATTERY_RUNTIME 1
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT
#define TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT 0
#endif

#elif TRACKER_BUILD_IS_PRODUCTION

#ifndef TRACKER_ENABLE_SERIAL_CONSOLE
#define TRACKER_ENABLE_SERIAL_CONSOLE 1
#endif
#ifndef TRACKER_ENABLE_BOOT_DELAY
#define TRACKER_ENABLE_BOOT_DELAY 0
#endif
#ifndef TRACKER_ENABLE_BOOT_BANNER
#define TRACKER_ENABLE_BOOT_BANNER 1
#endif
#ifndef TRACKER_ENABLE_SERIAL_CLI
#define TRACKER_ENABLE_SERIAL_CLI 1
#endif
#ifndef TRACKER_ENABLE_FULL_CLI
#define TRACKER_ENABLE_FULL_CLI 0
#endif
#ifndef TRACKER_ENABLE_BASIC_CLI
#define TRACKER_ENABLE_BASIC_CLI 1
#endif
#ifndef TRACKER_ENABLE_SETUP_COMMANDS
#define TRACKER_ENABLE_SETUP_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_CONFIG_COMMANDS
#define TRACKER_ENABLE_CONFIG_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_NETWORK_COMMANDS
#define TRACKER_ENABLE_NETWORK_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_COMMANDS
#define TRACKER_ENABLE_SLIMEVR_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_CALIBRATION_COMMANDS
#define TRACKER_ENABLE_CALIBRATION_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_TEST_COMMANDS
#define TRACKER_ENABLE_TEST_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_WIFI_SCAN_COMMANDS
#define TRACKER_ENABLE_WIFI_SCAN_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_MAG_COMMANDS
#define TRACKER_ENABLE_MAG_COMMANDS 1
#endif
#ifndef TRACKER_ENABLE_SERIAL_STREAM
#define TRACKER_ENABLE_SERIAL_STREAM 0
#endif
#ifndef TRACKER_ENABLE_MACHINE_LOG
#define TRACKER_ENABLE_MACHINE_LOG 0
#endif
#ifndef TRACKER_ENABLE_STATIC_TEST
#define TRACKER_ENABLE_STATIC_TEST 0
#endif
#ifndef TRACKER_ENABLE_RUNTIME_TEST
#define TRACKER_ENABLE_RUNTIME_TEST 0
#endif
#ifndef TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS
#define TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS 0
#endif
#ifndef TRACKER_ENABLE_HOTPATH_PERF
#define TRACKER_ENABLE_HOTPATH_PERF 0
#endif
#ifndef TRACKER_ENABLE_LOOP_TIMING
#define TRACKER_ENABLE_LOOP_TIMING 0
#endif
#ifndef TRACKER_ENABLE_BOOT_HEARTBEAT
#define TRACKER_ENABLE_BOOT_HEARTBEAT 0
#endif
#ifndef TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT
#define TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT 1
#endif
#ifndef TRACKER_ENABLE_STATUS_LED
#define TRACKER_ENABLE_STATUS_LED 1
#endif
#ifndef TRACKER_ENABLE_TAP_RUNTIME
#define TRACKER_ENABLE_TAP_RUNTIME 1
#endif
#ifndef TRACKER_ENABLE_BATTERY_RUNTIME
#define TRACKER_ENABLE_BATTERY_RUNTIME 1
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT
#define TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT 1
#endif

#elif TRACKER_BUILD_IS_SLIM

#ifndef TRACKER_ENABLE_SERIAL_CONSOLE
#define TRACKER_ENABLE_SERIAL_CONSOLE 0
#endif
#ifndef TRACKER_ENABLE_BOOT_DELAY
#define TRACKER_ENABLE_BOOT_DELAY 0
#endif
#ifndef TRACKER_ENABLE_BOOT_BANNER
#define TRACKER_ENABLE_BOOT_BANNER 0
#endif
#ifndef TRACKER_ENABLE_SERIAL_CLI
#define TRACKER_ENABLE_SERIAL_CLI 0
#endif
#ifndef TRACKER_ENABLE_FULL_CLI
#define TRACKER_ENABLE_FULL_CLI 0
#endif
#ifndef TRACKER_ENABLE_BASIC_CLI
#define TRACKER_ENABLE_BASIC_CLI 0
#endif
#ifndef TRACKER_ENABLE_SETUP_COMMANDS
#define TRACKER_ENABLE_SETUP_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_CONFIG_COMMANDS
#define TRACKER_ENABLE_CONFIG_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_NETWORK_COMMANDS
#define TRACKER_ENABLE_NETWORK_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_COMMANDS
#define TRACKER_ENABLE_SLIMEVR_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_CALIBRATION_COMMANDS
#define TRACKER_ENABLE_CALIBRATION_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_TEST_COMMANDS
#define TRACKER_ENABLE_TEST_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_WIFI_SCAN_COMMANDS
#define TRACKER_ENABLE_WIFI_SCAN_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_MAG_COMMANDS
#define TRACKER_ENABLE_MAG_COMMANDS 0
#endif
#ifndef TRACKER_ENABLE_SERIAL_STREAM
#define TRACKER_ENABLE_SERIAL_STREAM 0
#endif
#ifndef TRACKER_ENABLE_MACHINE_LOG
#define TRACKER_ENABLE_MACHINE_LOG 0
#endif
#ifndef TRACKER_ENABLE_STATIC_TEST
#define TRACKER_ENABLE_STATIC_TEST 0
#endif
#ifndef TRACKER_ENABLE_RUNTIME_TEST
#define TRACKER_ENABLE_RUNTIME_TEST 0
#endif
#ifndef TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS
#define TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS 0
#endif
#ifndef TRACKER_ENABLE_HOTPATH_PERF
#define TRACKER_ENABLE_HOTPATH_PERF 0
#endif
#ifndef TRACKER_ENABLE_LOOP_TIMING
#define TRACKER_ENABLE_LOOP_TIMING 0
#endif
#ifndef TRACKER_ENABLE_BOOT_HEARTBEAT
#define TRACKER_ENABLE_BOOT_HEARTBEAT 0
#endif
#ifndef TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT
#define TRACKER_ENABLE_PREPARED_OUTPUT_SNAPSHOT 1
#endif
#ifndef TRACKER_ENABLE_STATUS_LED
#define TRACKER_ENABLE_STATUS_LED 0
#endif
#ifndef TRACKER_ENABLE_TAP_RUNTIME
#define TRACKER_ENABLE_TAP_RUNTIME 0
#endif
#ifndef TRACKER_ENABLE_BATTERY_RUNTIME
#define TRACKER_ENABLE_BATTERY_RUNTIME 0
#endif
#ifndef TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT
#define TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT 0
#endif

#endif
