#pragma once

#include "build_config/build_profiles.hpp"
#include "build_config/feature_flags.hpp"

// Network / SlimeVR transport defaults.
// TRACKER_WIFI_TX_POWER intentionally references the ESP32 Arduino WiFi enum
// token, but is kept as a macro so board profiles can override it from
// platformio build_flags or by editing build_config/network_tuning.hpp. It is
// only consumed by the ESP32 Wi-Fi adapter implementation after including WiFi.h.
#ifndef TRACKER_WIFI_APPLY_TX_POWER_AFTER_BEGIN
#define TRACKER_WIFI_APPLY_TX_POWER_AFTER_BEGIN 1
#endif

#ifndef TRACKER_WIFI_TX_POWER
#define TRACKER_WIFI_TX_POWER WIFI_POWER_8_5dBm
#endif


#ifndef TRACKER_WIFI_CONNECT_TIMEOUT_MS
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_WIFI_CONNECT_TIMEOUT_MS 20000UL
  #else
    #define TRACKER_WIFI_CONNECT_TIMEOUT_MS 15000UL
  #endif
#endif

#ifndef TRACKER_WIFI_RECONNECT_BACKOFF_MS
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_WIFI_RECONNECT_BACKOFF_MS 10000UL
  #else
    #define TRACKER_WIFI_RECONNECT_BACKOFF_MS 5000UL
  #endif
#endif

#ifndef TRACKER_WIFI_STATUS_POLL_INTERVAL_MS
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_WIFI_STATUS_POLL_INTERVAL_MS 500UL
  #else
    #define TRACKER_WIFI_STATUS_POLL_INTERVAL_MS 250UL
  #endif
#endif

// 0 means the app calls Wi-Fi/SlimeVR runtime every loop. Slim uses a small
// scheduler interval to avoid spinning the network state machine thousands of
// times per second while still keeping latency well below its RotationData
// period.
#ifndef TRACKER_NETWORK_RUNTIME_UPDATE_INTERVAL_MS
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_NETWORK_RUNTIME_UPDATE_INTERVAL_MS 5UL
  #else
    #define TRACKER_NETWORK_RUNTIME_UPDATE_INTERVAL_MS 0UL
  #endif
#endif

#ifndef TRACKER_SLIMEVR_DISCOVERY_INTERVAL_MS
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_DISCOVERY_INTERVAL_MS 2000UL
  #else
    #define TRACKER_SLIMEVR_DISCOVERY_INTERVAL_MS 1000UL
  #endif
#endif

#ifndef TRACKER_SLIMEVR_INCOMING_PACKETS_PER_UPDATE
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_INCOMING_PACKETS_PER_UPDATE 1
  #else
    #define TRACKER_SLIMEVR_INCOMING_PACKETS_PER_UPDATE 4
  #endif
#endif

#ifndef TRACKER_SLIMEVR_OUTPUT_RATE_HZ_MAX
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_OUTPUT_RATE_HZ_MAX 50
  #else
    #define TRACKER_SLIMEVR_OUTPUT_RATE_HZ_MAX 1000
  #endif
#endif

#ifndef TRACKER_SLIMEVR_RUNTIME_CONFIG_REFRESH_MS
  #if TRACKER_BUILD_IS_DEBUG
    #define TRACKER_SLIMEVR_RUNTIME_CONFIG_REFRESH_MS 0UL
  #elif TRACKER_BUILD_IS_PRODUCTION
    #define TRACKER_SLIMEVR_RUNTIME_CONFIG_REFRESH_MS 250UL
  #else
    #define TRACKER_SLIMEVR_RUNTIME_CONFIG_REFRESH_MS 1000UL
  #endif
#endif

#ifndef TRACKER_SLIMEVR_TELEMETRY_INTERVAL_MS
  #if TRACKER_BUILD_IS_DEBUG
    #define TRACKER_SLIMEVR_TELEMETRY_INTERVAL_MS 5000UL
  #elif TRACKER_BUILD_IS_PRODUCTION
    #define TRACKER_SLIMEVR_TELEMETRY_INTERVAL_MS 15000UL
  #else
    #define TRACKER_SLIMEVR_TELEMETRY_INTERVAL_MS 0UL
  #endif
#endif

#ifndef TRACKER_SLIMEVR_ENABLE_SIGNAL_TELEMETRY
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_ENABLE_SIGNAL_TELEMETRY 0
  #else
    #define TRACKER_SLIMEVR_ENABLE_SIGNAL_TELEMETRY 1
  #endif
#endif

#ifndef TRACKER_SLIMEVR_ENABLE_TEMPERATURE_TELEMETRY
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_ENABLE_TEMPERATURE_TELEMETRY 0
  #else
    #define TRACKER_SLIMEVR_ENABLE_TEMPERATURE_TELEMETRY 1
  #endif
#endif

#ifndef TRACKER_SLIMEVR_ENABLE_BATTERY_TELEMETRY
  #if TRACKER_BUILD_IS_SLIM
    #define TRACKER_SLIMEVR_ENABLE_BATTERY_TELEMETRY 0
  #else
    #define TRACKER_SLIMEVR_ENABLE_BATTERY_TELEMETRY 1
  #endif
#endif

#ifndef TRACKER_SLIMEVR_SERVER_SILENCE_TIMEOUT_MS
#define TRACKER_SLIMEVR_SERVER_SILENCE_TIMEOUT_MS 15000UL
#endif

#ifndef TRACKER_SLIMEVR_SEND_FAILURE_REOPEN_THRESHOLD
#define TRACKER_SLIMEVR_SEND_FAILURE_REOPEN_THRESHOLD 5UL
#endif
