#pragma once

#include "build_config/build_profiles.hpp"
#include "build_config/feature_flags.hpp"
#include "build_config/runtime_tuning.hpp"
#include "build_config/network_tuning.hpp"

// Derived feature groups for application/runtime code.
//
// Low-level TRACKER_ENABLE_* macros describe individual modules. Code that only
// needs to know whether a subsystem exists should prefer the TRACKER_HAS_*
// aliases below. This keeps profile policy centralized and reduces scattered
// combinations such as:
//   #if TRACKER_ENABLE_STATIC_TEST || TRACKER_ENABLE_BOOT_HEARTBEAT
// across app/runtime glue.

#ifndef TRACKER_HAS_SERIAL_CONSOLE
#define TRACKER_HAS_SERIAL_CONSOLE TRACKER_ENABLE_SERIAL_CONSOLE
#endif

#ifndef TRACKER_HAS_SERIAL_CLI
#define TRACKER_HAS_SERIAL_CLI TRACKER_ENABLE_SERIAL_CLI
#endif

#ifndef TRACKER_HAS_BASIC_CLI
#define TRACKER_HAS_BASIC_CLI TRACKER_ENABLE_BASIC_CLI
#endif

#ifndef TRACKER_HAS_FULL_CLI
#define TRACKER_HAS_FULL_CLI TRACKER_ENABLE_FULL_CLI
#endif

#ifndef TRACKER_HAS_WIFI_REMOTE_CONSOLE
#define TRACKER_HAS_WIFI_REMOTE_CONSOLE TRACKER_ENABLE_WIFI_REMOTE_CONSOLE
#endif

#ifndef TRACKER_HAS_SETUP_UI
#define TRACKER_HAS_SETUP_UI TRACKER_ENABLE_SETUP_COMMANDS
#endif

#ifndef TRACKER_HAS_CALIBRATION_UI
#define TRACKER_HAS_CALIBRATION_UI TRACKER_ENABLE_CALIBRATION_COMMANDS
#endif

#ifndef TRACKER_HAS_TEST_UI
#define TRACKER_HAS_TEST_UI TRACKER_ENABLE_TEST_COMMANDS
#endif

#ifndef TRACKER_HAS_SERIAL_STREAM
#define TRACKER_HAS_SERIAL_STREAM TRACKER_ENABLE_SERIAL_STREAM
#endif

#ifndef TRACKER_HAS_SERIAL_STREAM_STATE
#define TRACKER_HAS_SERIAL_STREAM_STATE (TRACKER_ENABLE_SERIAL_CLI || TRACKER_ENABLE_SERIAL_STREAM || TRACKER_ENABLE_BOOT_HEARTBEAT)
#endif

#ifndef TRACKER_HAS_MACHINE_LOG
#define TRACKER_HAS_MACHINE_LOG TRACKER_ENABLE_MACHINE_LOG
#endif

#ifndef TRACKER_HAS_STATIC_TEST
#define TRACKER_HAS_STATIC_TEST TRACKER_ENABLE_STATIC_TEST
#endif

#ifndef TRACKER_HAS_GYRO_TEMP_FIT
#define TRACKER_HAS_GYRO_TEMP_FIT (TRACKER_ENABLE_STATIC_TEST || TRACKER_ENABLE_SETUP_COMMANDS)
#endif

#ifndef TRACKER_HAS_RUNTIME_TEST
#define TRACKER_HAS_RUNTIME_TEST TRACKER_ENABLE_RUNTIME_TEST
#endif

#ifndef TRACKER_HAS_BOOT_HEARTBEAT
#define TRACKER_HAS_BOOT_HEARTBEAT TRACKER_ENABLE_BOOT_HEARTBEAT
#endif

#ifndef TRACKER_HAS_STATIC_TEST_STATE
#define TRACKER_HAS_STATIC_TEST_STATE (TRACKER_ENABLE_STATIC_TEST || TRACKER_ENABLE_BOOT_HEARTBEAT)
#endif

#ifndef TRACKER_HAS_RUNTIME_TEST_STATE
#define TRACKER_HAS_RUNTIME_TEST_STATE (TRACKER_ENABLE_RUNTIME_TEST || TRACKER_ENABLE_BOOT_HEARTBEAT)
#endif


#ifndef TRACKER_HAS_CALIBRATION_AUTONOMY
#define TRACKER_HAS_CALIBRATION_AUTONOMY TRACKER_ENABLE_CALIBRATION_AUTONOMY
#endif

#ifndef TRACKER_HAS_RUNTIME_PROFILER
#define TRACKER_HAS_RUNTIME_PROFILER TRACKER_ENABLE_RUNTIME_PROFILER
#endif

#ifndef TRACKER_HAS_RUNTIME_DIAGNOSTICS
#define TRACKER_HAS_RUNTIME_DIAGNOSTICS (TRACKER_ENABLE_STATIC_TEST || TRACKER_ENABLE_RUNTIME_TEST || TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS || TRACKER_ENABLE_HOTPATH_PERF || TRACKER_ENABLE_LOOP_TIMING || TRACKER_ENABLE_RUNTIME_PROFILER)
#endif

#ifndef TRACKER_HAS_HOTPATH_PERF
#define TRACKER_HAS_HOTPATH_PERF (TRACKER_ENABLE_HOTPATH_PERF || TRACKER_ENABLE_STATIC_TEST || TRACKER_ENABLE_RUNTIME_TEST)
#endif

#ifndef TRACKER_HAS_PRODUCT_TELEMETRY
#define TRACKER_HAS_PRODUCT_TELEMETRY (TRACKER_SLIMEVR_ENABLE_SIGNAL_TELEMETRY || TRACKER_SLIMEVR_ENABLE_TEMPERATURE_TELEMETRY || TRACKER_SLIMEVR_ENABLE_BATTERY_TELEMETRY)
#endif

#ifndef TRACKER_HAS_BATTERY_RUNTIME
#define TRACKER_HAS_BATTERY_RUNTIME TRACKER_ENABLE_BATTERY_RUNTIME
#endif

#ifndef TRACKER_HAS_STATUS_LED
#define TRACKER_HAS_STATUS_LED TRACKER_ENABLE_STATUS_LED
#endif

#ifndef TRACKER_HAS_TAP_RUNTIME
#define TRACKER_HAS_TAP_RUNTIME TRACKER_ENABLE_TAP_RUNTIME
#endif

#ifndef TRACKER_HAS_MOTION_LIGHT_SLEEP
#define TRACKER_HAS_MOTION_LIGHT_SLEEP TRACKER_ENABLE_MOTION_LIGHT_SLEEP
#endif

#ifndef TRACKER_HAS_CONSOLE_SUPPRESS
#define TRACKER_HAS_CONSOLE_SUPPRESS TRACKER_ENABLE_CONSOLE_SUPPRESS
#endif

#ifndef TRACKER_HAS_DETAILED_RUNTIME_STATUS
#define TRACKER_HAS_DETAILED_RUNTIME_STATUS TRACKER_ENABLE_DETAILED_RUNTIME_STATUS
#endif

#ifndef TRACKER_HAS_DETAILED_MAG_STATUS
#define TRACKER_HAS_DETAILED_MAG_STATUS TRACKER_ENABLE_DETAILED_MAG_STATUS
#endif

#ifndef TRACKER_HAS_FULL_CONFIG_PRINT
#define TRACKER_HAS_FULL_CONFIG_PRINT TRACKER_ENABLE_FULL_CONFIG_PRINT
#endif

// Contract checks. These catch profile/source-filter drift at compile time
// before it turns into linker-only undefined references or unused module builds.

#if TRACKER_CLI_IS_NONE && TRACKER_ENABLE_SERIAL_CLI
#error "TRACKER_CLI_LEVEL_NONE requires TRACKER_ENABLE_SERIAL_CLI=0."
#endif

#if !TRACKER_CLI_IS_NONE && !TRACKER_ENABLE_SERIAL_CLI
#error "A BASIC/FULL CLI level requires TRACKER_ENABLE_SERIAL_CLI=1."
#endif

#if TRACKER_ENABLE_SERIAL_CLI && !TRACKER_ENABLE_SERIAL_CONSOLE
#error "Serial CLI requires TRACKER_ENABLE_SERIAL_CONSOLE=1."
#endif

#if TRACKER_ENABLE_BASIC_CLI && !TRACKER_ENABLE_SERIAL_CLI
#error "TRACKER_ENABLE_BASIC_CLI requires TRACKER_ENABLE_SERIAL_CLI=1."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && !TRACKER_ENABLE_SERIAL_CLI
#error "Wi-Fi remote console reuses the CLI dispatcher and requires TRACKER_ENABLE_SERIAL_CLI=1."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_PORT == 0)
#error "TRACKER_REMOTE_CONSOLE_PORT must be non-zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_BYTES_PER_LOOP == 0)
#error "TRACKER_REMOTE_CONSOLE_BYTES_PER_LOOP must be greater than zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_QUEUE_BYTES == 0)
#error "TRACKER_SERIAL_OUTPUT_QUEUE_BYTES must be greater than zero when Serial is enabled."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_RECORD_BYTES == 0)
#error "TRACKER_SERIAL_OUTPUT_RECORD_BYTES must be greater than zero when Serial is enabled."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_RECORD_BYTES > TRACKER_SERIAL_OUTPUT_QUEUE_BYTES)
#error "TRACKER_SERIAL_OUTPUT_RECORD_BYTES must fit inside TRACKER_SERIAL_OUTPUT_QUEUE_BYTES."
#endif

#if TRACKER_ENABLE_MACHINE_LOG && TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_RECORD_BYTES < 384)
#error "LOGVER3 requires at least 384 bytes of line-atomic serial record staging."
#endif

#if TRACKER_ENABLE_MACHINE_LOG && TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_QUEUE_BYTES < 1280)
#error "LOGVER3 full bundles require at least 1280 bytes of serial queue admission."
#endif


#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_BYTES_PER_DRAIN == 0)
#error "TRACKER_SERIAL_OUTPUT_BYTES_PER_DRAIN must be greater than zero when Serial is enabled."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_DRAIN_INTERVAL_MS == 0)
#error "TRACKER_SERIAL_OUTPUT_DRAIN_INTERVAL_MS must be greater than zero when Serial is enabled."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_STALL_BACKOFF_MAX_MS < TRACKER_SERIAL_OUTPUT_DRAIN_INTERVAL_MS)
#error "TRACKER_SERIAL_OUTPUT_STALL_BACKOFF_MAX_MS must not be below the normal drain interval."
#endif

#if TRACKER_ENABLE_SERIAL_CONSOLE && (TRACKER_SERIAL_OUTPUT_STALE_DISCARD_MS == 0)
#error "TRACKER_SERIAL_OUTPUT_STALE_DISCARD_MS must be greater than zero when Serial is enabled."
#endif


#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_QUEUE_BYTES == 0)
#error "TRACKER_REMOTE_CONSOLE_OUTPUT_QUEUE_BYTES must be greater than zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_RECORD_BYTES == 0)
#error "TRACKER_REMOTE_CONSOLE_OUTPUT_RECORD_BYTES must be greater than zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_RECORD_BYTES > TRACKER_REMOTE_CONSOLE_OUTPUT_QUEUE_BYTES)
#error "TRACKER_REMOTE_CONSOLE_OUTPUT_RECORD_BYTES must fit inside TRACKER_REMOTE_CONSOLE_OUTPUT_QUEUE_BYTES."
#endif

#if TRACKER_ENABLE_MACHINE_LOG && TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_RECORD_BYTES < 384)
#error "LOGVER3 requires at least 384 bytes of line-atomic remote record staging."
#endif


#if TRACKER_ENABLE_MACHINE_LOG && TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_QUEUE_BYTES < 1280)
#error "LOGVER3 full bundles require at least 1280 bytes of remote queue admission."
#endif


#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_BYTES_PER_DRAIN == 0)
#error "TRACKER_REMOTE_CONSOLE_OUTPUT_BYTES_PER_DRAIN must be greater than zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_OUTPUT_DRAIN_INTERVAL_MS == 0)
#error "TRACKER_REMOTE_CONSOLE_OUTPUT_DRAIN_INTERVAL_MS must be greater than zero when Wi-Fi remote console is enabled."
#endif

#if TRACKER_ENABLE_WIFI_REMOTE_CONSOLE && (TRACKER_REMOTE_CONSOLE_SESSION_LEASE_MS < 5000UL)
#error "TRACKER_REMOTE_CONSOLE_SESSION_LEASE_MS must allow bounded host keepalives."
#endif

#if TRACKER_DIAGNOSTIC_TIMING_SAMPLE_DIVISOR == 0
#error "TRACKER_DIAGNOSTIC_TIMING_SAMPLE_DIVISOR must be non-zero."
#endif

#if TRACKER_STATIC_TEST_STATS_BLOCK_SAMPLES == 0
#error "TRACKER_STATIC_TEST_STATS_BLOCK_SAMPLES must be non-zero."
#endif

#if TRACKER_MACHINE_LOG_QUEUE_RECORDS == 0 || TRACKER_MACHINE_LOG_QUEUE_RECORDS > 255
#error "TRACKER_MACHINE_LOG_QUEUE_RECORDS must fit the uint8_t ring indices."
#endif

#if TRACKER_MACHINE_LOG_LINES_PER_SERVICE == 0 || TRACKER_MACHINE_LOG_LINES_PER_SERVICE > 8
#error "TRACKER_MACHINE_LOG_LINES_PER_SERVICE must be 1..8."
#endif

#if TRACKER_ENABLE_MACHINE_LOG && (TRACKER_MACHINE_LOG_NETWORK_PERIOD_US == 0)
#error "TRACKER_MACHINE_LOG_NETWORK_PERIOD_US must be non-zero."
#endif

#if TRACKER_ENABLE_FULL_CLI && !TRACKER_ENABLE_BASIC_CLI
#error "TRACKER_ENABLE_FULL_CLI requires TRACKER_ENABLE_BASIC_CLI=1."
#endif

#if TRACKER_ENABLE_SETUP_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "Setup commands require the serial CLI."
#endif

#if TRACKER_ENABLE_CONFIG_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "Config commands require the serial CLI."
#endif

#if TRACKER_ENABLE_NETWORK_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "Network commands require the serial CLI."
#endif

#if TRACKER_ENABLE_SLIMEVR_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "SlimeVR commands require the serial CLI."
#endif

#if TRACKER_ENABLE_CALIBRATION_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "Calibration commands require the serial CLI. Slim should apply NVS calibration only."
#endif

#if TRACKER_ENABLE_CALIBRATION_AUTONOMY && !TRACKER_ENABLE_CALIBRATION_CANDIDATES
#error "Calibration autonomy requires calibration candidate storage."
#endif

#if TRACKER_ENABLE_TEST_COMMANDS && !TRACKER_ENABLE_SERIAL_CLI
#error "Test commands require the serial CLI."
#endif

#if TRACKER_ENABLE_STATIC_TEST && !TRACKER_ENABLE_SERIAL_CLI
#error "Static test runner is command-driven and requires the serial CLI."
#endif

#if TRACKER_ENABLE_RUNTIME_TEST && !TRACKER_ENABLE_SERIAL_CLI
#error "Runtime test runner is command-driven and requires the serial CLI."
#endif

#if TRACKER_ENABLE_SLIMEVR_SERIAL_COMPAT && !TRACKER_ENABLE_SERIAL_CLI
#error "SlimeVR serial compatibility commands require the serial CLI."
#endif

#if TRACKER_ENABLE_SERIAL_STREAM && !TRACKER_ENABLE_SERIAL_CONSOLE
#error "Serial stream requires the serial console."
#endif

#if TRACKER_ENABLE_MACHINE_LOG && !TRACKER_ENABLE_SERIAL_CONSOLE
#error "Machine log requires the serial console."
#endif

#if TRACKER_ENABLE_BOOT_HEARTBEAT && !TRACKER_ENABLE_SERIAL_CONSOLE
#error "Boot heartbeat requires the serial console."
#endif

#if TRACKER_ENABLE_RUNTIME_POWER_DIAGNOSTICS && !TRACKER_ENABLE_RUNTIME_TEST
#error "Runtime power diagnostics are reported by the runtime test runner."
#endif

#if TRACKER_ENABLE_RUNTIME_PROFILER && !TRACKER_ENABLE_SERIAL_CLI
#error "Runtime profiler is a live serial/telnet diagnostic and requires serial CLI."
#endif

#if TRACKER_ENABLE_TAP_DIAGNOSTICS && !TRACKER_ENABLE_TAP_RUNTIME
#error "Tap diagnostics require TRACKER_ENABLE_TAP_RUNTIME=1."
#endif

#if TRACKER_ENABLE_TAP_DIAGNOSTICS && !TRACKER_ENABLE_SERIAL_CLI
#error "Tap diagnostics are controlled through the serial/telnet CLI and require TRACKER_ENABLE_SERIAL_CLI=1."
#endif

#if TRACKER_ENABLE_HOTPATH_PERF && !TRACKER_HAS_RUNTIME_DIAGNOSTICS
#error "Hot-path perf counters require a diagnostics-capable profile."
#endif

#if TRACKER_ENABLE_DETAILED_RUNTIME_STATUS && !TRACKER_ENABLE_SERIAL_CLI
#error "Detailed runtime status is a CLI feature."
#endif

#if TRACKER_ENABLE_DETAILED_MAG_STATUS && !TRACKER_ENABLE_SERIAL_CLI
#error "Detailed mag status is a CLI feature."
#endif

#if TRACKER_ENABLE_FULL_CONFIG_PRINT && !TRACKER_ENABLE_CONFIG_COMMANDS
#error "Full config print requires config commands."
#endif

#if TRACKER_ENABLE_IDLE_YIELD && (TRACKER_IDLE_YIELD_MODE != TRACKER_IDLE_YIELD_MODE_DELAY0) && (TRACKER_IDLE_YIELD_MODE != TRACKER_IDLE_YIELD_MODE_DELAY1)
#error "TRACKER_IDLE_YIELD_MODE must be TRACKER_IDLE_YIELD_MODE_DELAY0 or TRACKER_IDLE_YIELD_MODE_DELAY1 when idle yield is enabled."
#endif

#if TRACKER_ENABLE_IDLE_YIELD && (TRACKER_IDLE_YIELD_EVERY_N_IDLE_LOOPS == 0)
#error "TRACKER_IDLE_YIELD_EVERY_N_IDLE_LOOPS must be greater than zero."
#endif

#if (TRACKER_OPTIONAL_SHORT_SERVICE_MIN_SLACK_US == 0) ||     (TRACKER_OPTIONAL_CONSOLE_SERVICE_MIN_SLACK_US == 0) ||     (TRACKER_OPTIONAL_BACKGROUND_SERVICE_MIN_SLACK_US == 0)
#error "Optional runtime service slack thresholds must be non-zero."
#endif
#if (TRACKER_OPTIONAL_SHORT_SERVICE_MIN_SLACK_US > 10000UL) ||     (TRACKER_OPTIONAL_CONSOLE_SERVICE_MIN_SLACK_US > 10000UL) ||     (TRACKER_OPTIONAL_BACKGROUND_SERVICE_MIN_SLACK_US > 10000UL)
#error "Optional runtime service slack thresholds must fit the 10 ms output frame."
#endif
#if TRACKER_IMU_STAGE_PROFILER_SAMPLE_DIVISOR == 0
#error "TRACKER_IMU_STAGE_PROFILER_SAMPLE_DIVISOR must be greater than zero."
#endif
#if TRACKER_ENABLE_MOTION_LIGHT_SLEEP && !defined(ARDUINO_ARCH_ESP32)
#error "TRACKER_ENABLE_MOTION_LIGHT_SLEEP requires the Arduino ESP32 target."
#endif

#if TRACKER_ENABLE_MOTION_LIGHT_SLEEP && (TRACKER_MOTION_LIGHT_SLEEP_SERVER_ABSENCE_MS == 0)
#error "TRACKER_MOTION_LIGHT_SLEEP_SERVER_ABSENCE_MS must be greater than zero when motion light sleep is enabled."
#endif

#if TRACKER_ENABLE_MOTION_LIGHT_SLEEP && (TRACKER_MOTION_LIGHT_SLEEP_WAKE_THRESHOLD > 63)
#error "TRACKER_MOTION_LIGHT_SLEEP_WAKE_THRESHOLD must fit LSM6DSV WAKE_UP_THS bits [5:0]."
#endif

#if TRACKER_ENABLE_MOTION_LIGHT_SLEEP && (TRACKER_MOTION_LIGHT_SLEEP_WAKE_DURATION > 3)
#error "TRACKER_MOTION_LIGHT_SLEEP_WAKE_DURATION must fit LSM6DSV WAKE_UP_DUR bits [1:0]."
#endif

#if TRACKER_ENABLE_MOTION_LIGHT_SLEEP && (TRACKER_MOTION_LIGHT_SLEEP_ACCEL_ODR != 30) && (TRACKER_MOTION_LIGHT_SLEEP_ACCEL_ODR != 60)
#error "TRACKER_MOTION_LIGHT_SLEEP_ACCEL_ODR supports only 30 or 60 Hz."
#endif
