#include "app/tracker_command_wiring.hpp"

namespace tracker {

void wireTrackerCommandContext(TrackerSerialCommandContext& ctx,
                                      const TrackerCommandRuntimeObjects& objects,
                                      const TrackerCommandRuntimeHooks& hooks) {
    ctx = TrackerSerialCommandContext{};

    ctx.io = objects.io;
    ctx.config = objects.config;
    ctx.configStore = objects.configStore;
    ctx.networkConfig = objects.networkConfig;
    ctx.networkConfigStore = objects.networkConfigStore;
    ctx.networkConfigLoadedFromNvs = objects.networkConfigLoadedFromNvs;
    ctx.wifiManager = objects.wifiManager;
    ctx.slimevrRuntime = objects.slimevrRuntime;
    ctx.lsm = objects.lsm;
    ctx.fifo = objects.fifo;
    ctx.sensorHub = objects.sensorHub;
    ctx.mag = objects.mag;
    ctx.imuCal = objects.imuCal;
    ctx.gyroTempComp = objects.gyroTempComp;
    ctx.quality = objects.quality;
    ctx.ahrs = objects.ahrs;
    ctx.calibrationIo = objects.calibrationIo;
    ctx.accelCalRunner = objects.accelCalRunner;
    ctx.gyroTempCapture = objects.gyroTempCapture;
    ctx.lastMagProcessed = objects.lastMagProcessed;
    ctx.lastScaledSample = objects.lastScaledSample;
    ctx.lastCalibratedSample = objects.lastCalibratedSample;
    ctx.lastImuSampleSequence = objects.lastImuSampleSequence;
    ctx.streamState = objects.streamState;
    ctx.logState = objects.logState;

    ctx.resetFifoRuntime = hooks.resetFifoRuntime;
    ctx.resetFifoRuntimeUser = hooks.resetFifoRuntimeUser;
    ctx.resetAhrsRuntime = hooks.resetAhrsRuntime;
    ctx.resetAhrsRuntimeUser = hooks.resetAhrsRuntimeUser;
    ctx.printRuntimeStatus = hooks.printRuntimeStatus;
    ctx.printRuntimeStatusUser = hooks.printRuntimeStatusUser;
    ctx.printRuntimeHealth = hooks.printRuntimeHealth;
    ctx.printRuntimeHealthUser = hooks.printRuntimeHealthUser;
    ctx.setSpiFrequency = hooks.setSpiFrequency;
    ctx.setSpiFrequencyUser = hooks.setSpiFrequencyUser;
    ctx.emitLogHeader = hooks.emitLogHeader;
    ctx.emitLogHeaderUser = hooks.emitLogHeaderUser;
    ctx.printLogSummary = hooks.printLogSummary;
    ctx.printLogSummaryUser = hooks.printLogSummaryUser;
    ctx.resetLogCounters = hooks.resetLogCounters;
    ctx.resetLogCountersUser = hooks.resetLogCountersUser;
    ctx.printRuntimeGyroBiasStatus = hooks.printRuntimeGyroBiasStatus;
    ctx.printRuntimeGyroBiasStatusUser = hooks.printRuntimeGyroBiasStatusUser;
    ctx.setRuntimeGyroBiasEnabled = hooks.setRuntimeGyroBiasEnabled;
    ctx.setRuntimeGyroBiasEnabledUser = hooks.setRuntimeGyroBiasEnabledUser;
    ctx.resetRuntimeGyroBiasEstimator = hooks.resetRuntimeGyroBiasEstimator;
    ctx.resetRuntimeGyroBiasEstimatorUser = hooks.resetRuntimeGyroBiasEstimatorUser;
    ctx.startStaticTest = hooks.startStaticTest;
    ctx.startStaticTestUser = hooks.startStaticTestUser;
    ctx.stopStaticTest = hooks.stopStaticTest;
    ctx.stopStaticTestUser = hooks.stopStaticTestUser;
    ctx.printStaticTestStatus = hooks.printStaticTestStatus;
    ctx.printStaticTestStatusUser = hooks.printStaticTestStatusUser;

    ctx.startRuntimeTest = hooks.startRuntimeTest;
    ctx.startRuntimeTestUser = hooks.startRuntimeTestUser;
    ctx.stopRuntimeTest = hooks.stopRuntimeTest;
    ctx.stopRuntimeTestUser = hooks.stopRuntimeTestUser;
    ctx.printRuntimeTestStatus = hooks.printRuntimeTestStatus;
    ctx.printRuntimeTestStatusUser = hooks.printRuntimeTestStatusUser;
    ctx.setMagRuntimeEnabled = hooks.setMagRuntimeEnabled;
    ctx.setMagRuntimeEnabledUser = hooks.setMagRuntimeEnabledUser;
    ctx.printMagRuntimeStatus = hooks.printMagRuntimeStatus;
    ctx.printMagRuntimeStatusUser = hooks.printMagRuntimeStatusUser;
    ctx.printMagProcessedStatus = hooks.printMagProcessedStatus;
    ctx.printMagProcessedStatusUser = hooks.printMagProcessedStatusUser;
    ctx.printMagHeadingStatus = hooks.printMagHeadingStatus;
    ctx.printMagHeadingStatusUser = hooks.printMagHeadingStatusUser;
    ctx.setMagHeadingReference = hooks.setMagHeadingReference;
    ctx.setMagHeadingReferenceUser = hooks.setMagHeadingReferenceUser;
    ctx.clearMagHeadingReference = hooks.clearMagHeadingReference;
    ctx.clearMagHeadingReferenceUser = hooks.clearMagHeadingReferenceUser;
    ctx.setMagHeadingAutoReferenceEnabled = hooks.setMagHeadingAutoReferenceEnabled;
    ctx.setMagHeadingAutoReferenceEnabledUser = hooks.setMagHeadingAutoReferenceEnabledUser;
    ctx.printMagYawCorrectionStatus = hooks.printMagYawCorrectionStatus;
    ctx.printMagYawCorrectionStatusUser = hooks.printMagYawCorrectionStatusUser;
    ctx.resetMagYawCorrection = hooks.resetMagYawCorrection;
    ctx.resetMagYawCorrectionUser = hooks.resetMagYawCorrectionUser;
    ctx.setMagYawCorrectionApplyEnabled = hooks.setMagYawCorrectionApplyEnabled;
    ctx.setMagYawCorrectionApplyEnabledUser = hooks.setMagYawCorrectionApplyEnabledUser;
    ctx.startMagCalibration = hooks.startMagCalibration;
    ctx.startMagCalibrationUser = hooks.startMagCalibrationUser;
    ctx.stopMagCalibration = hooks.stopMagCalibration;
    ctx.stopMagCalibrationUser = hooks.stopMagCalibrationUser;
    ctx.resetMagCalibration = hooks.resetMagCalibration;
    ctx.resetMagCalibrationUser = hooks.resetMagCalibrationUser;
    ctx.applyMagCalibration = hooks.applyMagCalibration;
    ctx.applyMagCalibrationUser = hooks.applyMagCalibrationUser;
    ctx.printMagCalibrationStatus = hooks.printMagCalibrationStatus;
    ctx.printMagCalibrationStatusUser = hooks.printMagCalibrationStatusUser;
    ctx.fitGyroTempFromLastStatic = hooks.fitGyroTempFromLastStatic;
    ctx.fitGyroTempFromLastStaticUser = hooks.fitGyroTempFromLastStaticUser;
    ctx.fitGyroTempFromCapture = hooks.fitGyroTempFromCapture;
    ctx.fitGyroTempFromCaptureUser = hooks.fitGyroTempFromCaptureUser;
    ctx.fitGyroTempFromCaptureRam = hooks.fitGyroTempFromCaptureRam;
    ctx.fitGyroTempFromCaptureRamUser = hooks.fitGyroTempFromCaptureRamUser;
    ctx.serviceCalibrationRuntime = hooks.serviceCalibrationRuntime;
    ctx.serviceCalibrationRuntimeUser = hooks.serviceCalibrationRuntimeUser;
}

} // namespace tracker
